name: 🚀 Deploy website on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    if: github.event_name != 'pull_request'
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftpupload.net
        username: if0_34772199
        password: ${{ secrets.ftp_password }}
        protocol: ftps
        server-dir: ./htdocs/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          db_connect.php
          secrets.php
          domain.php
